# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/userdb
    username: user
    password: userpassword

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: user-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Ensure this matches your Eureka server URL
    register-with-eureka: true
    fetch-registry: true